[edge_drone]
group_uuid = 1
uuid = 1
iface = "eth0"
rx_ignore_self_injected = 1
rx_ring_size = 4096
stream_id = 1001
bandwidth = 20
group = [0,2]
internal_uuid = 99
internal_stream_id = 2001
[edge_drone.position]
x = -1.5
y = 1.0
z = 0.0
